/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PawnableLoan {
  export type LoanStruct = {
    loanId: string;
    borrower: AddressLike;
    lender: AddressLike;
    loanToken: AddressLike;
    loanAmount: BigNumberish;
    repayAmount: BigNumberish;
    collateralNFT: AddressLike;
    collateralTokenIds: BigNumberish[];
    dueTimestamp: BigNumberish;
    status: BigNumberish;
    createdAt: BigNumberish;
    matchedAt: BigNumberish;
    closedAt: BigNumberish;
  };

  export type LoanStructOutput = [
    loanId: string,
    borrower: string,
    lender: string,
    loanToken: string,
    loanAmount: bigint,
    repayAmount: bigint,
    collateralNFT: string,
    collateralTokenIds: bigint[],
    dueTimestamp: bigint,
    status: bigint,
    createdAt: bigint,
    matchedAt: bigint,
    closedAt: bigint
  ] & {
    loanId: string;
    borrower: string;
    lender: string;
    loanToken: string;
    loanAmount: bigint;
    repayAmount: bigint;
    collateralNFT: string;
    collateralTokenIds: bigint[];
    dueTimestamp: bigint;
    status: bigint;
    createdAt: bigint;
    matchedAt: bigint;
    closedAt: bigint;
  };
}

export interface PawnableLoanInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MIN_LOAN_AMOUNT"
      | "MIN_LOAN_DURATION"
      | "cancelLoan"
      | "collectedFees"
      | "getLoan"
      | "getUserLoans"
      | "isLiquidatable"
      | "liquidateLoan"
      | "loans"
      | "matchLoan"
      | "owner"
      | "platformFeeBps"
      | "renounceOwnership"
      | "repayLoan"
      | "requestLoan"
      | "setPlatformFee"
      | "transferOwnership"
      | "userLoans"
      | "withdrawFees"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FeeCollected"
      | "LoanCancelled"
      | "LoanLiquidated"
      | "LoanMatched"
      | "LoanRepaid"
      | "LoanRequested"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MIN_LOAN_AMOUNT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_LOAN_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cancelLoan", values: [string]): string;
  encodeFunctionData(
    functionFragment: "collectedFees",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getLoan", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getUserLoans",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isLiquidatable",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateLoan",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [string]): string;
  encodeFunctionData(functionFragment: "matchLoan", values: [string]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "platformFeeBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "repayLoan", values: [string]): string;
  encodeFunctionData(
    functionFragment: "requestLoan",
    values: [
      string,
      AddressLike,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish[],
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setPlatformFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userLoans",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawFees",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MIN_LOAN_AMOUNT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_LOAN_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancelLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "collectedFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserLoans",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isLiquidatable",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "liquidateLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "matchLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "platformFeeBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestLoan",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPlatformFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "userLoans", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawFees",
    data: BytesLike
  ): Result;
}

export namespace FeeCollectedEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanCancelledEvent {
  export type InputTuple = [loanId: string, borrower: AddressLike];
  export type OutputTuple = [loanId: string, borrower: string];
  export interface OutputObject {
    loanId: string;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanLiquidatedEvent {
  export type InputTuple = [
    loanId: string,
    lender: AddressLike,
    collateralCount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: string,
    lender: string,
    collateralCount: bigint
  ];
  export interface OutputObject {
    loanId: string;
    lender: string;
    collateralCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanMatchedEvent {
  export type InputTuple = [
    loanId: string,
    borrower: AddressLike,
    lender: AddressLike,
    loanAmount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: string,
    borrower: string,
    lender: string,
    loanAmount: bigint
  ];
  export interface OutputObject {
    loanId: string;
    borrower: string;
    lender: string;
    loanAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [
    loanId: string,
    borrower: AddressLike,
    repayAmount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: string,
    borrower: string,
    repayAmount: bigint
  ];
  export interface OutputObject {
    loanId: string;
    borrower: string;
    repayAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRequestedEvent {
  export type InputTuple = [
    loanId: string,
    borrower: AddressLike,
    loanToken: AddressLike,
    loanAmount: BigNumberish,
    repayAmount: BigNumberish,
    dueTimestamp: BigNumberish
  ];
  export type OutputTuple = [
    loanId: string,
    borrower: string,
    loanToken: string,
    loanAmount: bigint,
    repayAmount: bigint,
    dueTimestamp: bigint
  ];
  export interface OutputObject {
    loanId: string;
    borrower: string;
    loanToken: string;
    loanAmount: bigint;
    repayAmount: bigint;
    dueTimestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PawnableLoan extends BaseContract {
  connect(runner?: ContractRunner | null): PawnableLoan;
  waitForDeployment(): Promise<this>;

  interface: PawnableLoanInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MIN_LOAN_AMOUNT: TypedContractMethod<[], [bigint], "view">;

  MIN_LOAN_DURATION: TypedContractMethod<[], [bigint], "view">;

  cancelLoan: TypedContractMethod<[loanId: string], [void], "nonpayable">;

  collectedFees: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  getLoan: TypedContractMethod<
    [loanId: string],
    [PawnableLoan.LoanStructOutput],
    "view"
  >;

  getUserLoans: TypedContractMethod<[user: AddressLike], [string[]], "view">;

  isLiquidatable: TypedContractMethod<[loanId: string], [boolean], "view">;

  liquidateLoan: TypedContractMethod<[loanId: string], [void], "nonpayable">;

  loans: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        loanId: string;
        borrower: string;
        lender: string;
        loanToken: string;
        loanAmount: bigint;
        repayAmount: bigint;
        collateralNFT: string;
        dueTimestamp: bigint;
        status: bigint;
        createdAt: bigint;
        matchedAt: bigint;
        closedAt: bigint;
      }
    ],
    "view"
  >;

  matchLoan: TypedContractMethod<[loanId: string], [void], "nonpayable">;

  owner: TypedContractMethod<[], [string], "view">;

  platformFeeBps: TypedContractMethod<[], [bigint], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayLoan: TypedContractMethod<[loanId: string], [void], "nonpayable">;

  requestLoan: TypedContractMethod<
    [
      loanId: string,
      loanToken: AddressLike,
      loanAmount: BigNumberish,
      repayAmount: BigNumberish,
      collateralNFT: AddressLike,
      collateralTokenIds: BigNumberish[],
      dueTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  setPlatformFee: TypedContractMethod<
    [newFeeBps: BigNumberish],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  userLoans: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  withdrawFees: TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MIN_LOAN_AMOUNT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_LOAN_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelLoan"
  ): TypedContractMethod<[loanId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "collectedFees"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [loanId: string],
    [PawnableLoan.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserLoans"
  ): TypedContractMethod<[user: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "isLiquidatable"
  ): TypedContractMethod<[loanId: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "liquidateLoan"
  ): TypedContractMethod<[loanId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        string,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        loanId: string;
        borrower: string;
        lender: string;
        loanToken: string;
        loanAmount: bigint;
        repayAmount: bigint;
        collateralNFT: string;
        dueTimestamp: bigint;
        status: bigint;
        createdAt: bigint;
        matchedAt: bigint;
        closedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "matchLoan"
  ): TypedContractMethod<[loanId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "platformFeeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[loanId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "requestLoan"
  ): TypedContractMethod<
    [
      loanId: string,
      loanToken: AddressLike,
      loanAmount: BigNumberish,
      repayAmount: BigNumberish,
      collateralNFT: AddressLike,
      collateralTokenIds: BigNumberish[],
      dueTimestamp: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPlatformFee"
  ): TypedContractMethod<[newFeeBps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userLoans"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "withdrawFees"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FeeCollected"
  ): TypedContractEvent<
    FeeCollectedEvent.InputTuple,
    FeeCollectedEvent.OutputTuple,
    FeeCollectedEvent.OutputObject
  >;
  getEvent(
    key: "LoanCancelled"
  ): TypedContractEvent<
    LoanCancelledEvent.InputTuple,
    LoanCancelledEvent.OutputTuple,
    LoanCancelledEvent.OutputObject
  >;
  getEvent(
    key: "LoanLiquidated"
  ): TypedContractEvent<
    LoanLiquidatedEvent.InputTuple,
    LoanLiquidatedEvent.OutputTuple,
    LoanLiquidatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanMatched"
  ): TypedContractEvent<
    LoanMatchedEvent.InputTuple,
    LoanMatchedEvent.OutputTuple,
    LoanMatchedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "LoanRequested"
  ): TypedContractEvent<
    LoanRequestedEvent.InputTuple,
    LoanRequestedEvent.OutputTuple,
    LoanRequestedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "FeeCollected(address,uint256)": TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;
    FeeCollected: TypedContractEvent<
      FeeCollectedEvent.InputTuple,
      FeeCollectedEvent.OutputTuple,
      FeeCollectedEvent.OutputObject
    >;

    "LoanCancelled(string,address)": TypedContractEvent<
      LoanCancelledEvent.InputTuple,
      LoanCancelledEvent.OutputTuple,
      LoanCancelledEvent.OutputObject
    >;
    LoanCancelled: TypedContractEvent<
      LoanCancelledEvent.InputTuple,
      LoanCancelledEvent.OutputTuple,
      LoanCancelledEvent.OutputObject
    >;

    "LoanLiquidated(string,address,uint256)": TypedContractEvent<
      LoanLiquidatedEvent.InputTuple,
      LoanLiquidatedEvent.OutputTuple,
      LoanLiquidatedEvent.OutputObject
    >;
    LoanLiquidated: TypedContractEvent<
      LoanLiquidatedEvent.InputTuple,
      LoanLiquidatedEvent.OutputTuple,
      LoanLiquidatedEvent.OutputObject
    >;

    "LoanMatched(string,address,address,uint256)": TypedContractEvent<
      LoanMatchedEvent.InputTuple,
      LoanMatchedEvent.OutputTuple,
      LoanMatchedEvent.OutputObject
    >;
    LoanMatched: TypedContractEvent<
      LoanMatchedEvent.InputTuple,
      LoanMatchedEvent.OutputTuple,
      LoanMatchedEvent.OutputObject
    >;

    "LoanRepaid(string,address,uint256)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "LoanRequested(string,address,address,uint256,uint256,uint256)": TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;
    LoanRequested: TypedContractEvent<
      LoanRequestedEvent.InputTuple,
      LoanRequestedEvent.OutputTuple,
      LoanRequestedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
