// Mock data for development without backend
export const mockUsers = [
  {
    user_id: "mock-user-1",
    wallet_address: "0x742d35Cc6634C0532925a3b844Bc9e7595f0bEb",
    nickname: "테스트 유저",
    email: "test@example.com",
  },
]

export const mockAssets = [
  {
    asset_id: "asset-1",
    name: "Ethereum",
    symbol: "ETH",
    blockchain: "ethereum",
    contract_address: "0x0000000000000000000000000000000000000000",
    asset_type: "cryptocurrency",
    decimals: 18,
  },
  {
    asset_id: "asset-2",
    name: "USD Coin",
    symbol: "USDC",
    blockchain: "ethereum",
    contract_address: "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48",
    asset_type: "cryptocurrency",
    decimals: 6,
  },
  {
    asset_id: "asset-3",
    name: "Bored Ape Yacht Club",
    symbol: "BAYC",
    blockchain: "ethereum",
    contract_address: "0xBC4CA0EdA7647A8aB7C2061c2E118A18a936f13D",
    asset_type: "nft",
    decimals: 0,
  },
]

export const mockLoans = [
  {
    loan_id: "loan-1",
    borrower_id: "mock-user-1",
    lender_id: null,
    loan_asset_id: "asset-2",
    loan_amount: 5000,
    interest_rate_pct: 8.5,
    total_repay_amount: 5425,
    status: "pending",
    created_at: new Date().toISOString(),
    matched_at: null,
    activated_at: null,
    repaid_at: null,
    liquidated_at: null,
    repay_due_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    collaterals: [
      {
        collateral_id: "col-1",
        loan_id: "loan-1",
        asset_id: "asset-1",
        amount: 2.5,
        token_id: null,
      },
    ],
  },
  {
    loan_id: "loan-2",
    borrower_id: "mock-user-2",
    lender_id: null,
    loan_asset_id: "asset-2",
    loan_amount: 10000,
    interest_rate_pct: 12.0,
    total_repay_amount: 11200,
    status: "pending",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    matched_at: null,
    activated_at: null,
    repaid_at: null,
    liquidated_at: null,
    repay_due_at: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000).toISOString(),
    collaterals: [
      {
        collateral_id: "col-2",
        loan_id: "loan-2",
        asset_id: "asset-3",
        amount: 1,
        token_id: "1234",
      },
    ],
  },
  {
    loan_id: "loan-3",
    borrower_id: "mock-user-3",
    lender_id: "mock-user-1",
    loan_asset_id: "asset-2",
    loan_amount: 3000,
    interest_rate_pct: 10.0,
    total_repay_amount: 3300,
    status: "active",
    created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    matched_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    activated_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    repaid_at: null,
    liquidated_at: null,
    repay_due_at: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000).toISOString(),
    collaterals: [
      {
        collateral_id: "col-3",
        loan_id: "loan-3",
        asset_id: "asset-1",
        amount: 1.2,
        token_id: null,
      },
    ],
  },
]
